### ISSUE TITLE
testing with extranious data splits

### ISSUE THREAD

**Issue by bnebgen-LANL** [lanl/hippynn#121]
When training completes, testing will occur over all data splits. This will include data from splits like 'failed_std_fac_forces'. Error handling needs to be added when testing such splits at the end of training so that failing to evaluate on those splits does not cause a full crash. Edits should be made around hippynn/experiment/routines.py line 362

Traceback (most recent call last):
  File "/usr/projects/ml4chem/envs/p311a-venado-alf/lib/python3.10/site-packages/hippynn/tools.py", line 53, in log_terminal
    yield file
  File "/users/bnebgen/energeticMaterials/retrain-DFT-01/HIPNN-HC-hypSearch-0.py", line 233, in <module>
    setup_and_train(
  File "/usr/projects/ml4chem/envs/p311a-venado-alf/lib/python3.10/site-packages/hippynn/experiment/routines.py", line 138, in setup_and_train
    return train_model(
  File "/usr/projects/ml4chem/envs/p311a-venado-alf/lib/python3.10/site-packages/hippynn/experiment/routines.py", line 322, in train_model
    test_model(
  File "/usr/projects/ml4chem/envs/p311a-venado-alf/lib/python3.10/site-packages/hippynn/experiment/routines.py", line 362, in test_model
    evaluation_data = collections.OrderedDict(
  File "/usr/projects/ml4chem/envs/p311a-venado-alf/lib/python3.10/site-packages/hippynn/experiment/routines.py", line 364, in <genexpr>
    (key, database.make_generator(key, "eval", batch_size))
  File "/usr/projects/ml4chem/envs/p311a-venado-alf/lib/python3.10/site-packages/hippynn/databases/database.py", line 446, in make_generator
    data = [self.splits[split_name][k] for k in self.var_list]
  File "/usr/projects/ml4chem/envs/p311a-venado-alf/lib/python3.10/site-packages/hippynn/databases/database.py", line 446, in <listcomp>
    data = [self.splits[split_name][k] for k in self.var_list]
KeyError: 'energyperatom'

**Comment by lubbersnick** [comment]
Addressed in #123
